name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build web app
      run: npm run build:web
    
    - name: Setup Capacitor
      run: |
        npm install @capacitor/cli @capacitor/ios
        npx cap add ios
    
    - name: Build iOS app
      run: |
        npx cap copy ios
        npx cap build ios
    
    - name: Archive iOS app
      run: |
        xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release -destination generic/platform=iOS -archivePath App.xcarchive archive
    
    - name: Export IPA
      run: |
        xcodebuild -exportArchive -archivePath App.xcarchive -exportPath . -exportOptionsPlist exportOptions.plist
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Molaris-App
        path: App.ipa
